# Generated by Django 5.0.3 on 2024-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
