# Generated by Django 5.0.2 on 2024-03-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comuns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
    ]
