# Generated by Django 5.0.2 on 2024-03-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_time_divisao_atual_time_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='image',
            field=models.ImageField(null=True, upload_to='imagem'),
        ),
    ]
