# Generated by Django 5.0.2 on 2024-03-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0009_rename_titulocompetiçao_titulodascompetições_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulodascompetições',
            options={'verbose_name': 'Título', 'verbose_name_plural': 'Título'},
        ),
    ]
