# Generated by Django 5.0.3 on 2024-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'FERMININO'), ('M', 'MASCULINO')], max_length=120)),
                ('dt_nasc', models.PositiveIntegerField(default=False)),
                ('tel', models.PositiveIntegerField(default=False)),
                ('cpf', models.PositiveIntegerField(default=False)),
            ],
        ),
    ]
