# Generated by Django 5.0.2 on 2024-02-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano_fundaçao", models.PositiveIntegerField(default=False)),
                (
                    "divisao_atual",
                    models.CharField(
                        choices=[
                            ("A", "SERIE A"),
                            ("B", "SERIE B"),
                            ("C", "SERIE C"),
                            ("D", "SERIE D"),
                        ],
                        max_length=120,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
