# Generated by Django 5.0.2 on 2024-02-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_image_time_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="time",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Macho"), ("F", "Fêmea")], max_length=32, null=True
            ),
        ),
    ]
