# Generated by Django 5.0.2 on 2024-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='divisao_atual',
            field=models.CharField(choices=[('A', 'SÉRIE A'), ('B', 'SÉRIE B'), ('C', 'SÉRIE C'), ('D', 'SÉRIE D')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='sexo',
            field=models.CharField(choices=[('F', 'FERMININO'), ('M', 'MASCULINO')], max_length=100, null=True),
        ),
    ]
