# Generated by Django 5.0.2 on 2024-03-02 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_time_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='imagem')),
                ('nome', models.CharField(max_length=100)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogador', to='core.time')),
            ],
        ),
    ]
