# Generated by Django 5.0.2 on 2024-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jogador_num_camisa_jogador_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competiçao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('competiçoes_tp', models.CharField(choices=[('UF', 'Estadual'), ('NL', 'Nacional'), ('IN', 'Internacional')], max_length=180, null=True)),
            ],
        ),
    ]
