# Generated by Django 5.0.2 on 2024-03-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_competiçao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competiçao',
            old_name='competiçoes_tp',
            new_name='Tipo_da_competição',
        ),
    ]
