# Generated by Django 5.0.2 on 2024-03-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_competiçao_categoria_titulocompetiçao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TituloCompetiçao',
            new_name='TitulodasCompetições',
        ),
        migrations.AlterModelOptions(
            name='competiçao',
            options={'verbose_name': 'Competição', 'verbose_name_plural': 'Competições'},
        ),
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AlterModelOptions(
            name='titulodascompetições',
            options={'verbose_name': 'Competição', 'verbose_name_plural': 'Competições'},
        ),
    ]
