# Generated by Django 5.0.2 on 2024-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_titulodascompetições_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='pais',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='uf',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
