# Generated by Django 5.0.2 on 2024-02-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='ano_fundaçao',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='time',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('RS', 'Rio Grande do Sul'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='tem_mundial',
            field=models.BooleanField(default=False),
        ),
    ]
