# Generated by Django 5.0.2 on 2024-02-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_time_cores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('clube', models.CharField(max_length=100)),
                ('posiçao_principal', models.CharField(max_length=30)),
            ],
        ),
    ]
